import { h2, h3, p, ul, type BlogArticle } from "@/lib/blog/types";

export const article: BlogArticle = {
  slug: "choisir-ecole-maternelle-mohammedia",
  title: "Comment choisir une école maternelle à Mohammedia : le guide complet",
  description:
    "Guide pratique pour choisir une école maternelle à Mohammedia : critères de visite, langues, encadrement, trajet et questions à poser avant d'inscrire.",
  category: "Choisir son école",
  datePublished: "2026-09-23",
  dateModified: "2026-09-23",
  related: [
    "ecole-maternelle-la-coline-mohammedia",
    "questions-avant-inscrire-ecole-privee",
    "a-quel-age-commencer-maternelle",
  ],
  pillar: "/maternelle",
  published: true,
  image: "/media/images/ecole-maternelle-mohammedia-facade.webp",
  body: [
    p("Choisir une école maternelle à Mohammedia n'est pas un exercice de comparaison de brochures. C'est trouver un lieu où votre enfant pourra se sentir en sécurité, curieux et suffisamment accompagné pour oser. Le quartier, le trajet du matin, les langues réellement parlées en classe et la façon dont l'équipe accueille les familles comptent autant que le bâtiment."),
    p("Mot de Passe Junior se situe à Mohammedia, au quartier La Coline. L'école propose un parcours [préscolaire](/prescolaire), [maternelle](/maternelle) et [primaire](/primaire), avec un enseignement en français, arabe et anglais. Ce guide reste volontairement général : il vous aide à comparer n'importe quelle école de la ville, y compris la nôtre, sans remplacer une visite."),
    h2("Ce que les familles de Mohammedia regardent vraiment"),
    p("À Mohammedia, les parents hésitent souvent entre proximité, projet pédagogique et ambiance. Une école « bien notée » sur une conversation de quartier n'est pas forcément celle qui convient à votre enfant. Un enfant très moteur n'a pas les mêmes besoins qu'un enfant qui a besoin de temps pour se séparer. Partez de lui, pas d'une liste de prestiges."),
    p("Le trajet du matin pèse plus qu'on ne le dit. Un quart d'heure de trop, chaque jour, fatigue l'enfant avant même l'accueil. Si vous habitez La Coline, El Alia, un immeuble proche du boulevard de la Résistance ou un autre secteur de la ville, testez le parcours à l'heure réelle, pas un dimanche après-midi."),
    h3("Le cadre, pas seulement la façade"),
    p("Lors de la visite, observez la circulation : comment on entre, où l'on se déchausse ou range le cartable, comment un enfant en larmes est pris en charge. Une cour trop petite n'est pas toujours un problème si les sorties sont pensées. Une cour immense ne suffit pas si personne n'observe vraiment le jeu."),
    p("Regardez aussi les classes à hauteur d'enfant : affichages, coins calmes, accès à l'eau, toilettes. Demandez à voir un espace « réel » en activité, pas seulement une salle rangée pour les visiteurs. Si l'école ne peut pas le faire ce jour-là, convenez d'un autre passage."),
    h2("Les critères utiles, sans checklist infinie"),
    p("Vous n'avez pas besoin de vingt indicateurs. Cinq questions suffisent souvent à départager deux établissements."),
    ul(
      "Comment se passe l'accueil des premiers jours, et qui reste avec l'enfant si la séparation est difficile ?",
      "Quelles langues sont réellement utilisées dans la journée, et par qui ?",
      "Combien d'adultes encadrent le groupe, et que se passe-t-il à la pause ou à la sortie ?",
      "Comment l'école communique-t-elle avec les familles en cas de doute, de fièvre ou de conflit entre enfants ?",
      "Que se passe-t-il ensuite : y a-t-il une suite en primaire dans le même lieu, ou un changement d'établissement ?",
    ),
    p("Sur les langues, méfiez-vous des formules trop lisses. « On est trilingue » ne dit rien. Demandez un exemple concret : une chanson, un rituel du matin, un atelier. À Mot de Passe Junior, le projet [trilingue](/trilingue) s'appuie sur le français au quotidien, l'arabe comme ancrage, et une place importante de l'anglais dès le plus jeune âge. Ailleurs, l'équilibre peut être différent. L'important est que ce qui est dit soit visible."),
    h3("L'effectif et l'âge des enfants"),
    p("Le nombre d'enfants par classe n'est pas un trophée. Un groupe trop grand fatigue les adultes et réduit le temps réellement accordé à chaque enfant. Un groupe trop hétérogène en âge peut aussi compliquer le rythme. Demandez l'âge minimum et la répartition, puis vérifiez si cela correspond à votre enfant. [DONNÉE ÉCOLE À CONFIRMER : âge minimum exact et effectif par classe à Mot de Passe Junior]."),
    h2("La visite : le meilleur filtre"),
    p("Une visite d'une heure en dit plus qu'une heure de lecture. Venez si possible avec la personne qui fera les trajets au quotidien. Observez comment on vous accueille : on vous écoute, ou on vous récite un discours ? Posez une question simple sur un cas concret (« mon enfant n'aime pas la sieste », « il parle surtout darija à la maison »). La réponse vous dira si l'équipe pense enfants ou procédures."),
    p("Si vous comparez plusieurs écoles maternelles à Mohammedia, notez le soir même trois impressions : le corps de l'enfant (aurait-il envie d'y rester ?), le vôtre (vous êtes-vous senti respecté ?), et une phrase entendue qui vous a marqué. Ces notes valent mieux qu'une grille de notes sur vingt."),
    h3("Ce qu'il ne faut pas surinterpréter"),
    p("Un local neuf n'est pas une pédagogie. Un local plus ancien n'est pas un défaut. Des photos très travaillées sur les réseaux ne disent rien du mercredi matin en novembre. À l'inverse, une école discrète en ligne peut très bien accompagner les enfants. Gardez les réseaux pour ce qu'ils sont : un aperçu, pas une preuve."),
    h2("Inscription : avancez sans vous précipiter"),
    p("À Mohammedia comme ailleurs, certaines écoles ferment leurs listes tôt. Cela ne justifie pas de signer le jour de la première visite. Prenez le temps de relire le règlement, les modalités de paiement et ce qui se passe en cas de désistement. [DONNÉE ÉCOLE À CONFIRMER : tarifs, frais d'inscription et calendrier exact des places à Mot de Passe Junior]."),
    p("Si le niveau n'est pas encore clair — préscolaire ou maternelle — lisez aussi [Préscolaire ou maternelle : quelle différence au Maroc ?](/blog/prescolaire-ou-maternelle-maroc) et [À quel âge commencer la maternelle ?](/blog/a-quel-age-commencer-maternelle). L'équipe peut vous orienter selon l'âge, sans remplacer votre jugement de parent."),
    h2("Et après la maternelle ?"),
    p("Beaucoup de familles de Mohammedia choisissent une maternelle sans regarder la suite. Or un enfant qui s'attache à un lieu, à des adultes et à des rituels vit mieux une continuité. Demandez si l'école propose un [primaire](/primaire) sur place, et comment se fait le passage. Ce n'est pas obligatoire que tout soit dans le même bâtiment. C'est utile de le savoir avant de s'engager."),
    p("Pour Mot de Passe Junior, le fil est le même d'un cycle à l'autre : apprendre, découvrir, grandir, réussir. Le détail du projet maternelle est sur la page dédiée. Les [inscriptions](/inscriptions) 2026-2027 se discutent ensuite, souvent d'abord par WhatsApp, puis lors d'une visite."),
    p("Si vous voulez un regard complémentaire, lisez aussi [5 questions à poser avant d'inscrire son enfant dans une école privée](/blog/questions-avant-inscrire-ecole-privee). Et si La Coline est votre quartier, l'article [École maternelle à La Coline](/blog/ecole-maternelle-la-coline-mohammedia) précise ce que les familles regardent souvent dans ce secteur."),
  ],
};
