import { h2, h3, p, ul, type BlogArticle } from "@/lib/blog/types";

export const article: BlogArticle = {
  slug: "prescolaire-ou-maternelle-maroc",
  title: "Préscolaire ou maternelle : quelle différence au Maroc ?",
  description:
    "Préscolaire et maternelle au Maroc : ce que ces mots recouvrent pour les parents, comment s'y retrouver selon l'âge, et quoi demander à l'école.",
  category: "Petite enfance & développement",
  datePublished: "2026-09-23",
  dateModified: "2026-09-23",
  related: [
    "a-quel-age-commencer-maternelle",
    "choisir-ecole-maternelle-mohammedia",
    "role-du-jeu-apprentissages-maternelle",
  ],
  pillar: "/prescolaire",
  published: true,
  image: "/media/images/ecole-maternelle-mohammedia-classe-prescolaire.webp",
  body: [
    p("Au Maroc, les mots « préscolaire » et « maternelle » se recouvrent souvent dans les conversations de parents. On les entend dans les écoles privées, sur les groupes de quartier, parfois dans les documents officiels. Pourtant, ils ne décrivent pas toujours la même chose. D'une ville à l'autre, d'un établissement à l'autre, le même enfant de quatre ans peut être dit « en préscolaire » ou « en maternelle »."),
    p("Cet article clarifie le vocabulaire pour les familles de Mohammedia, sans prétendre remplacer un texte ministériel. Il vous aide à poser les bonnes questions à l'école, y compris à Mot de Passe Junior, où le [préscolaire](/prescolaire) ouvre le parcours avant la [maternelle](/maternelle) et le [primaire](/primaire)."),
    h2("Ce que recouvre souvent le préscolaire"),
    p("Dans le langage des familles, le préscolaire désigne les premiers pas hors de la maison : se séparer, jouer en groupe, découvrir des routines, commencer à tenir un crayon, écouter une histoire. L'accent est mis sur l'adaptation, le jeu et la socialisation plus que sur un programme scolaire visible."),
    p("Côté politiques publiques, le préscolaire renvoie aussi à une étape éducative avant l'enseignement primaire, avec un effort national pour généraliser l'accueil des jeunes enfants. Les modalités concrètes varient : établissement public, école privée, unité dédiée. Pour un parent, le plus utile n'est pas le sigle. C'est le quotidien proposé à l'enfant."),
    h3("Ce que les parents observent concrètement"),
    p("Un préscolaire bien pensé ressemble rarement à une petite classe de CP. On y voit des coins jeu, du mouvement, des chansons, des ateliers courts. L'adulte accompagne plus qu'il ne « fait cours ». Si on vous montre surtout des cahiers dès la première année hors de la maison, demandez pourquoi. Ce n'est pas forcément mauvais. Cela doit être expliqué."),
    h2("Ce que recouvre souvent la maternelle"),
    p("« Maternelle » est le mot que beaucoup de familles francophones utilisent par habitude, en pensant aux cycles français. Au Maroc, dans le privé surtout, il désigne souvent un niveau déjà un peu plus structuré : plus de rituels collectifs, un début de graphisme plus volontaire, une préparation plus visible vers le primaire — tout en restant dans l'enfance."),
    p("La frontière n'est pas juridique dans la bouche des parents. Elle est pédagogique. Une maternelle peut encore être très ludique. Un préscolaire peut déjà demander beaucoup d'assise. D'où l'intérêt de visiter, plutôt que de choisir sur le nom de la section."),
    h3("Comment s'y retrouver en une phrase"),
    p("Si vous devez retenir une distinction simple : le préscolaire insiste souvent sur l'entrée dans le collectif et le jeu ; la maternelle insiste davantage sur la préparation aux apprentissages scolaires, sans que l'un doive tuer l'autre. À Mot de Passe Junior, le préscolaire est présenté comme le début de l'aventure — couleurs, jeux, espaces pour apprendre et s'amuser — et la maternelle prolonge ce chemin."),
    h2("L'âge, plus fiable que l'étiquette"),
    p("Deux enfants du même âge n'ont pas le même besoin. L'un est déjà à l'aise loin de ses parents. L'autre a besoin de plus de temps et de rituel. L'étiquette « maternelle » ne dit pas si votre enfant est prêt. L'observation, si."),
    ul(
      "Arrive-t-il à rester occupé quelques minutes sans un adulte collé à lui ?",
      "Supporte-t-il une courte séparation, même avec un peu de larmes ?",
      "A-t-il commencé à jouer près d'autres enfants, même sans encore « jouer avec » ?",
      "A-t-il un rythme de sieste ou de repas encore très différent de celui du groupe ?",
    ),
    p("Ces questions n'ont pas de score. Elles servent à parler avec l'école. L'article [À quel âge commencer la maternelle ?](/blog/a-quel-age-commencer-maternelle) développe ce point. [DONNÉE ÉCOLE À CONFIRMER : âge minimum exact et découpage des niveaux à Mot de Passe Junior]."),
    h2("Ce qu'il faut demander à l'école, quel que soit le nom"),
    p("Demandez à voir une journée type. Pas un planning décoratif : qui accueille, quand on joue dehors, quand on parle quelle langue, ce qui se passe si un enfant ne veut pas participer. Le [jeu](/blog/role-du-jeu-apprentissages-maternelle) devrait rester central, en préscolaire comme en maternelle. S'il disparaît au profit de fiches trop tôt, posez la question."),
    p("Demandez aussi la suite. Un enfant qui commence en préscolaire à Mohammedia a besoin de savoir, par ses parents, s'il pourra rester dans le même esprit en maternelle puis en primaire. La continuité rassure. Elle n'est pas obligatoire. Elle se décide en connaissance de cause."),
    h3("Langues : le même sujet, deux rythmes"),
    p("Que l'enfant soit dit en préscolaire ou en maternelle, les langues s'entendent. Elles ne s'apprennent pas comme une liste. Elles s'imprègnent. Sur ce point, voyez la page [trilingue](/trilingue). Un trop-plein de « cours » de langue trop tôt fatigue. Un bain naturel, répété, chanteur, suffit souvent à ouvrir l'oreille."),
    h2("Comment décider, concrètement"),
    p("Si votre enfant sort à peine de la maison, commencez par regarder le [préscolaire](/prescolaire). Si vous sentez qu'il a déjà besoin d'un cadre plus collectif et d'un pas vers les apprentissages, regardez la [maternelle](/maternelle). Si vous hésitez, dites-le. Une équipe honnête vous dira « venez, on verra ensemble », pas « inscrivez-vous dans la case la plus chère »."),
    p("Pour comparer les écoles de la ville, lisez [Comment choisir une école maternelle à Mohammedia](/blog/choisir-ecole-maternelle-mohammedia). Pour le calendrier de rentrée, voyez aussi [le calendrier scolaire 2026-2027](/blog/calendrier-scolaire-2026-2027-maroc-mohammedia). Les [inscriptions](/inscriptions) se discutent ensuite, souvent d'abord sur WhatsApp."),
  ],
};
