import { h2, h3, p, ul, type BlogArticle } from "@/lib/blog/types";

export const article: BlogArticle = {
  slug: "questions-avant-inscrire-ecole-privee",
  title: "5 questions à poser avant d'inscrire son enfant dans une école privée",
  description:
    "Cinq questions concrètes à poser avant d'inscrire un enfant dans une école privée à Mohammedia : encadrement, langues, adaptation, argent, suite du parcours.",
  category: "Choisir son école",
  datePublished: "2026-09-23",
  dateModified: "2026-09-23",
  related: [
    "choisir-ecole-maternelle-mohammedia",
    "ecole-maternelle-la-coline-mohammedia",
    "calendrier-scolaire-2026-2027-maroc-mohammedia",
  ],
  pillar: "/inscriptions",
  published: true,
  image: "/media/images/ecole-maternelle-mohammedia-facade.webp",
  body: [
    p("Une école privée se choisit rarement sur une vitrine. Elle se choisit sur des réponses. Pas des slogans : des réponses que vous pouvez vérifier en visitant, puis en relisant le règlement. Voici cinq questions qui, à Mohammedia comme ailleurs, départagent souvent deux établissements. Elles valent pour Mot de Passe Junior autant que pour une école voisine."),
    p("Complétez-les avec le [guide pour choisir une maternelle](/blog/choisir-ecole-maternelle-mohammedia) et, si vous habitez le quartier, l'article [La Coline](/blog/ecole-maternelle-la-coline-mohammedia). Les [inscriptions](/inscriptions) viennent après les réponses, pas avant."),
    h2("1. Qui s'occupe de mon enfant, concrètement ?"),
    p("Demandez le nombre d'adultes présents avec le groupe, y compris à la cour et à la sortie. « On est une équipe bienveillante » ne dit pas si, à 16 h, un seul adulte gère une file de parents et vingt cartables. Demandez aussi qui est la personne référente les premiers jours. Un enfant de maternelle s'attache à un visage."),
    p("[DONNÉE ÉCOLE À CONFIRMER : taux d'encadrement et organisation des récréations à Mot de Passe Junior]. Tant que le chiffre n'est pas dit, observez. Les regards dans la cour en disent plus qu'une plaquette."),
    h3("Question de relance"),
    p("« Que se passe-t-il si mon enfant se blesse légèrement, ou s'il ne veut plus entrer ? » La précision de la réponse compte autant que son contenu. Une procédure claire rassure. Une improvisation permanente, moins."),
    h2("2. Quelles langues sont vraiment parlées dans la journée ?"),
    p("Le privé aime les étiquettes : bilingue, trilingue, international. Demandez un exemple d'heure, pas un logo. Qui parle français, arabe, anglais ? Les enfants ont-ils le droit de répondre dans la langue qu'ils ont ? Y a-t-il des adultes qui ne comprennent pas la langue de la maison ?"),
    p("À Mot de Passe Junior, le projet est décrit sur la page [trilingue](/trilingue) et dans l'article [éducation trilingue dès le plus jeune âge](/blog/education-trilingue-jeune-age). [DONNÉE ÉCOLE À CONFIRMER : répartition horaire des langues]. Jugez aussi à l'oreille, le jour de la visite."),
    h2("3. Comment se passent les premières semaines ?"),
    p("C'est souvent là que se joue la confiance. Présence d'un parent, horaires aménagés, doudou, personne qui rappelle si la séparation est trop brutale : tout cela devrait pouvoir se dire. L'article [première rentrée en maternelle](/blog/premiere-rentree-maternelle-transition) prépare le côté famille. L'école doit préparer le sien. [DONNÉE ÉCOLE À CONFIRMER : protocole d'adaptation]."),
    p("Méfiez-vous de « ils s'habituent tous ». Certains s'habituent. D'autres ont besoin d'un pont. Une école privée n'est pas meilleure parce qu'elle est plus sévère le matin du 7 septembre."),
    h2("4. Qu'est-ce qui est inclus, et qu'est-ce qui s'ajoute ?"),
    p("Posez la question de l'argent sans gêne. Frais d'inscription, scolarité, fournitures, sorties, bus, restauration, « activités » facturées en octobre. Demandez ce qui arrive en cas de départ en cours d'année. [DONNÉE ÉCOLE À CONFIRMER : tarifs et conditions à Mot de Passe Junior]. Un établissement qui refuse d'en parler clairement vous dit déjà quelque chose."),
    p("Relisez le règlement avant de signer. Les belles visites n'annulent pas une clause que vous n'avez pas lue. Notez aussi le [calendrier](/blog/calendrier-scolaire-2026-2027-maroc-mohammedia) : les vacances nationales ne sont pas toujours celles de l'école."),
    h2("5. Que se passe-t-il après la maternelle ?"),
    p("Y a-t-il un [primaire](/primaire) sur place ? Un partenariat ? Un simple « on verra » ? La continuité n'est pas obligatoire. Elle se décide. Un enfant qui s'est attaché à un lieu vit mieux un passage pensé qu'un changement improvisé en juin."),
    p("Demandez aussi comment l'école parle des enfants en difficulté : langage, attention, séparation. « On n'a pas ce genre de cas » est rarement vrai. « On regarde avec la famille » est plus honnête."),
    h3("Après les cinq questions"),
    ul(
      "Notez les réponses le soir même.",
      "Comparez-les à ce que vous avez vu, pas seulement entendu.",
      "Reprenez [préscolaire ou maternelle](/blog/prescolaire-ou-maternelle-maroc) si le niveau n'est pas clair.",
      "Ne signez pas sous la pression d'une « dernière place » sans avoir lu.",
    ),
    p("Si ces questions trouvent des réponses justes à Mot de Passe Junior, la suite est simple : un message, une visite, puis la page [inscriptions](/inscriptions). Une école privée se mérite autant qu'elle vous choisit. Vous avez le droit de demander."),
    h2("Ce que ces questions ne remplacent pas"),
    p("Elles ne remplacent pas une visite. Elles ne remplacent pas le ressenti de votre enfant dans la cour. Elles ne remplacent pas la lecture du règlement. Elles évitent seulement de signer parce que « tout le quartier y va » ou parce qu'une place « part ce soir ». À La Coline comme ailleurs à Mohammedia, la rumeur est une donnée. Ce n'est pas une preuve."),
    p("Si le niveau n'est pas tranché, croisez avec [préscolaire ou maternelle](/blog/prescolaire-ou-maternelle-maroc) et [à quel âge commencer](/blog/a-quel-age-commencer-maternelle). Si les langues sont votre critère n°1, lisez le projet [trilingue](/trilingue). Puis posez les cinq questions à voix haute, stylo en main. Les silences, eux aussi, sont des réponses. Une école qui accepte le silence, et qui revient vers vous avec des faits, mérite souvent une deuxième visite."),
  ],
};
